fail_fast: true
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/ambv/black/
    rev: 22.1.0
    hooks:
      - id: black
        args: [--diff, --check]
  - repo: https://github.com/pycqa/flake8/
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort/
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--check-only]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        entry: mypy src/ tests/
        pass_filenames: false
        # verbose: true
